imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }

    # Sonata Bundles
    - { resource: sonata/sonata_admin.yml }
    #- { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }
    
    # Brickstorm
    - { resource: @BrickstormAmndrcBundle/Resources/config/config.yml }
    - { resource: @BrickstormSolidRBundle/Resources/config/config.yml }
    - { resource: @BrickstormWorldBundle/Resources/config/config.yml }
    - { resource: fos_socialnetworks.yml }

    - { resource: @IvoryGoogleMapBundle/Resources/config/services.xml }
    
    - { resource: @JMSPaymentCoreBundle/Resources/config/payment.xml }

framework:
    #esi:             ~
    translator: { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    form:
        resources:
            - 'SonataAdminBundle:Form:silex_form_div_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                user:     %database_user%
                host:     %database_host%
                password: %database_password%


        types:
            json: Sonata\Doctrine\Types\JsonType


    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: true

        #default_entity_manager:   default
        #entity_managers:
        #    default:
        #        #auto_mapping: true
        #        connection:       default
        #        mappings:
        #            StofDoctrineExtensionsBundle: true
        #    user:
        #        connection:       user
        #        mappings:
        #            ApplicationSonataUserBundle: ~
        #            SonataUserBundle: ~
        #            FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

jms_payment_core:
    secret: branchearmee

jms_payment_paypal:
    username: bbergstorm_api1.gmail.com
    password: M7EWDKLCCYDJFXTZ
    signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AT0llJncTZ1Dnvff7mfC7UxMPhVW


services:
    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }