fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: 422066694500806
    secret: 1b68fd9aadcf152867a44a1e68e32abb
    cookie: true
    permissions: [email, user_birthday, user_location]